// Code generated by github.com/iamolegga/rebus; DO NOT EDIT.

package bus

import (
	"github.com/iamolegga/rebusexample/internal/app"
)

type Bus interface { 
	GetTodoQueryExecutor
	GetAllTodosQueryExecutor
	CreateTodoCommandExecutor
	UpdateTodoCommandExecutor
	DeleteTodoCommandExecutor
	RegisterGetTodoQueryHandler(GetTodoQueryHandler)
	RegisterGetAllTodosQueryHandler(GetAllTodosQueryHandler)
	RegisterCreateTodoCommandHandler(CreateTodoCommandHandler)
	RegisterUpdateTodoCommandHandler(UpdateTodoCommandHandler)
	RegisterDeleteTodoCommandHandler(DeleteTodoCommandHandler)
}

type GetTodoQueryExecutor interface {
	ExecGetTodoQuery(app.GetTodoQuery) (app.GetTodoQueryResult, error)
}

type GetAllTodosQueryExecutor interface {
	ExecGetAllTodosQuery(app.GetAllTodosQuery) (app.GetAllTodosQueryResult, error)
}

type CreateTodoCommandExecutor interface {
	ExecCreateTodoCommand(app.CreateTodoCommand) (app.CreateTodoCommandResult, error)
}

type UpdateTodoCommandExecutor interface {
	ExecUpdateTodoCommand(app.UpdateTodoCommand) (app.UpdateTodoCommandResult, error)
}

type DeleteTodoCommandExecutor interface {
	ExecDeleteTodoCommand(app.DeleteTodoCommand) error
}

func New() Bus {
	return &bus{}
}

type bus struct { 
	GetTodoQueryHandler
	GetAllTodosQueryHandler
	CreateTodoCommandHandler
	UpdateTodoCommandHandler
	DeleteTodoCommandHandler
}

func (b *bus) ExecGetTodoQuery(input app.GetTodoQuery) (app.GetTodoQueryResult, error) {
	return b.GetTodoQueryHandler.Handle(input)
}

func (b *bus) ExecGetAllTodosQuery(input app.GetAllTodosQuery) (app.GetAllTodosQueryResult, error) {
	return b.GetAllTodosQueryHandler.Handle(input)
}

func (b *bus) ExecCreateTodoCommand(input app.CreateTodoCommand) (app.CreateTodoCommandResult, error) {
	return b.CreateTodoCommandHandler.Handle(input)
}

func (b *bus) ExecUpdateTodoCommand(input app.UpdateTodoCommand) (app.UpdateTodoCommandResult, error) {
	return b.UpdateTodoCommandHandler.Handle(input)
}

func (b *bus) ExecDeleteTodoCommand(input app.DeleteTodoCommand) error {
	return b.DeleteTodoCommandHandler.Handle(input)
}

func (b *bus) RegisterGetTodoQueryHandler(h GetTodoQueryHandler) {
	b.GetTodoQueryHandler = h
}

func (b *bus) RegisterGetAllTodosQueryHandler(h GetAllTodosQueryHandler) {
	b.GetAllTodosQueryHandler = h
}

func (b *bus) RegisterCreateTodoCommandHandler(h CreateTodoCommandHandler) {
	b.CreateTodoCommandHandler = h
}

func (b *bus) RegisterUpdateTodoCommandHandler(h UpdateTodoCommandHandler) {
	b.UpdateTodoCommandHandler = h
}

func (b *bus) RegisterDeleteTodoCommandHandler(h DeleteTodoCommandHandler) {
	b.DeleteTodoCommandHandler = h
}

type GetTodoQueryHandler interface {
	Handle(app.GetTodoQuery) (app.GetTodoQueryResult, error)
}

type GetAllTodosQueryHandler interface {
	Handle(app.GetAllTodosQuery) (app.GetAllTodosQueryResult, error)
}

type CreateTodoCommandHandler interface {
	Handle(app.CreateTodoCommand) (app.CreateTodoCommandResult, error)
}

type UpdateTodoCommandHandler interface {
	Handle(app.UpdateTodoCommand) (app.UpdateTodoCommandResult, error)
}

type DeleteTodoCommandHandler interface {
	Handle(app.DeleteTodoCommand) error
}
